# Dockerfile.flask
# Flask API for Customer Segmentation Model

# Step 1 — Base image
FROM python:3.11-slim

# Step 2 — Set working directory inside container
WORKDIR /app

# Step 3 — Copy requirements first (for caching)
COPY requirements.txt . 

# Step 4 — Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Step 5 — Copy source code and Flask app
COPY src/ ./src/
COPY flask_app.py .

# Step 6 — Expose port 5000
EXPOSE 5000
#this container expects to use port 5000

# Step 7 — Run Flask API
CMD ["python", "flask_app.py"]

# docker run -v ${PWD}/models:/app/models -p 5000:5000 customer-segmentation-api
# docker run -v ./models:/app/models -p 5000:5000 customer-segmentation-api