# infrastructure
services:   # "create these services for me"
  - type: web   #a web server that handles HTTP requests 
    name: customer-segmentation-fastapi
    env: docker
    dockerfilePath: ./Dockerfile.fastapi  
    dockerContext: .
    region: singapore  
    plan: free
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000