name: CI — Flask API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1 — Get your code
      - name: Checkout code
        uses: actions/checkout@v4
        # GitHub's official action that downloads repository code onto the runner machine.

      # Step 2 — Build Docker image
      - name: Build Docker image
        run: docker build -t customer-segmentation-api -f Dockerfile.flask .

      # Step 3 — Start Flask container
      - name: Run Flask container
        run: |
          docker run -d \
            -v ${{ github.workspace }}/models:/app/models \
            -p 5000:5000 \
            --name flask-api \
            customer-segmentation-api
          sleep 15

      # Step 4 — Install requests library
      - name: Install test dependencies
        run: pip install requests

      # Step 5 — Run API test
      - name: Run API test
        run: python test_api.py

      # Step 6 — Stop container
      - name: Stop container
        run: docker stop flask-api